### ISSUE TITLE
add puppy-io to vertx-awesome list

### ISSUE THREAD

**Issue by pmlopes** [loviworld/puppy-io#1]
Hi,

It would be nice to have this listed on:

https://github.com/vert-x3/vertx-awesome

**Comment by quebic-source** [comment]
Hi,
Thanks for reviewing my project. But my next version of this project running on the netty (not publish yet). At this time i'm not going to use use vertex. New version of my project contains inbuilt cluster mechanism, and messaging mechanism to doing micro-service. As soon as possible i will publish new version and i will let you know. Hope you will interest of my next version.

**Comment by pmlopes** [comment]
There is no reason to be listed if the goal is not to use vert.x in the future.
